## №1 (5 баллов)
### Напишите программы, которые создают следующие массивы NumPy:

In [ ]:
import numpy as np

In [ ]:
# 1. Массив со значениями 1, 7, 13, 105

# Создаем массив с заданными значениями
arr1 = np.array([1, 7, 13, 105])

# Проверяем использование памяти
print(f"Размер массива в памяти: {arr1.nbytes} байт")
print(f"Тип данных элементов: {arr1.dtype}")

# Сохраняем в текстовый файл
np.savetxt('array1.txt', arr1)
print("\nСодержимое текстового файла:")
with open('array1.txt', 'r') as f:
    print(f.read())

# Сохраняем в бинарный файл
np.save('array1.npy', arr1)

# Загружаем из бинарного файла
loaded_arr = np.load('array1.npy')
print("\nЗагруженный из бинарного файла массив:")
print(loaded_arr)

Размер массива в памяти: 32 байт
Тип данных элементов: int64

Содержимое текстового файла:
1.000000000000000000e+00
7.000000000000000000e+00
1.300000000000000000e+01
1.050000000000000000e+02


Загруженный из бинарного файла массив:
[  1   7  13 105]


In [ ]:
# 2. Три массива: нули, единицы, пятёрки
zeros = np.zeros(10, dtype=np.int8)  # Используем int8 для экономии памяти
ones = np.ones(10, dtype=np.int8)
fives = np.full(10, 5, dtype=np.int8)

print("Массивы из нулей, единиц и пятёрок:")
print("Нули:", zeros)
print("Единицы:", ones)
print("Пятёрки:", fives)

Массивы из нулей, единиц и пятёрок:
Нули: [0 0 0 0 0 0 0 0 0 0]
Единицы: [1 1 1 1 1 1 1 1 1 1]
Пятёрки: [5 5 5 5 5 5 5 5 5 5]


In [ ]:
# 3. Чётные числа от 30 до 70
evens = np.arange(30, 71, 2)
print("\nЧётные числа от 30 до 70:")
print(evens)


Чётные числа от 30 до 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [ ]:
# 4. Равномерное распределение от 5 до 50
uniform = np.linspace(5, 50, 10)
print("\nРавномерное распределение от 5 до 50:")
print(uniform)


Равномерное распределение от 5 до 50:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [ ]:
# 5. 3D массив 3x3x3 со случайными числами
rng = np.random.default_rng()
random_3d = rng.integers(1, 100, size=(3, 3, 3))
print("\n3D массив 3x3x3 со случайными числами:")
print(random_3d)


3D массив 3x3x3 со случайными числами:
[[[73 19 15]
  [57 37 23]
  [74 24 83]]

 [[ 2 25 12]
  [27 57 68]
  [38 49 41]]

 [[68 80 68]
  [40 74 53]
  [40 10 77]]]


In [ ]:
# 6. Матрица 3x4 с числами от 30 до 41
matrix_3x4 = np.arange(30, 42).reshape(3, 4)
print("\nМатрица 3x4 с числами от 30 до 41:")
print(matrix_3x4)


Матрица 3x4 с числами от 30 до 41:
[[30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]]


In [ ]:
# 7. Матрица 10x10 с единицами на границах
border_matrix = np.zeros((10, 10), dtype=np.int8)
border_matrix[:, 0] = border_matrix[:, -1] = 1
border_matrix[0, :] = border_matrix[-1, :] = 1
print("\nМатрица 10x10 с единицами на границах:")
print(border_matrix)


Матрица 10x10 с единицами на границах:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
# 8. Диагональная матрица 5x5
diag_matrix = np.zeros((5, 5), dtype=np.int8)
np.fill_diagonal(diag_matrix, np.arange(1, 6))
print("\nДиагональная матрица 5x5:")
print(diag_matrix)


Диагональная матрица 5x5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
# 9. Шахматный порядок с нулями на диагонали
chess = np.indices((4, 4)).sum(axis=0) % 2
np.fill_diagonal(chess, 0)
print("\nШахматный порядок 4x4 с нулями на диагонали:")
print(chess)


Шахматный порядок 4x4 с нулями на диагонали:
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [ ]:
# 10. Даты марта 2017
dates = np.arange('2017-03-01', '2017-04-01', dtype='datetime64[D]')
print("\nДни марта 2017 года:")
print(dates)


Дни марта 2017 года:
['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


# №2 (5 баллов)
### Напишите следующие программы, используя только подходящие функции модуля NumPy:

In [ ]:
# 1. Находение общих элементов между двумя массивами
import numpy as np

# Создаём тестовые массивы
arr1 = np.array([0, 10, 20, 40, 60])
arr2 = np.array([10, 30, 40])

# Находим общие элементы
common_elements = np.intersect1d(arr1, arr2)

print("Задача 1: Находение общих элементов")
print(f"Массив 1: {arr1}")
print(f"Массив 2: {arr2}")
print(f"Общие элементы: {common_elements}")

Задача 1: Находение общих элементов
Массив 1: [ 0 10 20 40 60]
Массив 2: [10 30 40]
Общие элементы: [10 40]


In [ ]:
# 2. Получение уникальных элементов
# Тестовый массив с повторяющимися элементами
arr = np.array([10, 10, 20, 20, 30, 30])

# Получаем уникальные элементы
unique_elements = np.unique(arr)

print("\nЗадача 2: Получение уникальных элементов")
print(f"Исходный массив: {arr}")
print(f"Уникальные элементы: {unique_elements}")


Задача 2: Получение уникальных элементов
Исходный массив: [10 10 20 20 30 30]
Уникальные элементы: [10 20 30]


In [ ]:
# Тест с многомерным массивом
arr_2d = np.array([[1, 1], [2, 3]])
unique_elements_2d = np.unique(arr_2d)

print("\nТест с многомерным массивом:")
print(f"Исходный массив:\n{arr_2d}")
print(f"Уникальные элементы: {unique_elements_2d}")


Тест с многомерным массивом:
Исходный массив:
[[1 1]
 [2 3]]
Уникальные элементы: [1 2 3]


In [ ]:
# 3. Получение уникальных элементов и их частот
arr = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

# Получаем уникальные элементы и их частоты
unique_elements, frequencies = np.unique(arr, return_counts=True)

print("\nЗадача 3: Получение уникальных элементов и их частот")
print(f"Исходный массив: {arr}")
print(f"Уникальные элементы: {unique_elements}")
print(f"Частоты: {frequencies}")


Задача 3: Получение уникальных элементов и их частот
Исходный массив: [10 10 20 10 20 20 20 30 30 50 40 40]
Уникальные элементы: [10 20 30 40 50]
Частоты: [3 4 2 2 1]


In [ ]:
# 4. Повторение массива
arr = np.array([1, 2, 3, 4])
print("\n4. Повторение массива:")
for i in range(1, 4):
    repeated = np.tile(arr, i)
    print(f"{i} повторение: {repeated}")


4. Повторение массива:
1 повторение: [1 2 3 4]
2 повторение: [1 2 3 4 1 2 3 4]
3 повторение: [1 2 3 4 1 2 3 4 1 2 3 4]


In [ ]:
# 5. Удаление значений nan
arr = np.array([200., 300., np.nan, np.nan, np.nan, 700.])
arr_without_nan = arr[~np.isnan(arr)]
print("\n5. Удаление значений nan:")
print(f"Исходный массив: {arr}")
print(f"Массив без nan: {arr_without_nan}")


5. Удаление значений nan:
Исходный массив: [200. 300.  nan  nan  nan 700.]
Массив без nan: [200. 300. 700.]


In [ ]:
# Пример с двумерным массивом
arr2d = np.array([[1., 2., 3.], [np.nan, 0., np.nan], [6., 7., np.nan]])
arr2d_without_nan = arr2d[~np.isnan(arr2d)]
print(f"\nДля двумерного массива:")
print(f"Исходный массив:\n{arr2d}")
print(f"Массив без nan: {arr2d_without_nan}")


Для двумерного массива:
Исходный массив:
[[ 1.  2.  3.]
 [nan  0. nan]
 [ 6.  7. nan]]
Массив без nan: [1. 2. 3. 0. 6. 7.]


In [ ]:
# 6. k наименьших значений
arr = np.array([1., 7., 8., 2., 0.1, 3., 15., 2.5])
k = 4
k_smallest = np.sort(arr)[:k]
print("\n6. k наименьших значений:")
print(f"Исходный массив: {arr}")
print(f"{k} наименьших значений: {k_smallest}")


6. k наименьших значений:
Исходный массив: [ 1.   7.   8.   2.   0.1  3.  15.   2.5]
4 наименьших значений: [0.1 1.  2.  2.5]


In [ ]:
# 7. Поиск ближайшего элемента
arr = np.array([0.5, 1.8, 2.1, 3.5, 4.87, 5.13, 6.49])
target = 3.09066280756759
nearest_idx = np.abs(arr - target).argmin()
nearest = arr[nearest_idx]
print("\n7. Поиск ближайшего элемента:")
print(f"Исходный массив: {arr}")
print(f"Целевое значение: {target}")
print(f"Ближайший элемент: {nearest}")


7. Поиск ближайшего элемента:
Исходный массив: [0.5  1.8  2.1  3.5  4.87 5.13 6.49]
Целевое значение: 3.09066280756759
Ближайший элемент: 3.5


In [ ]:
# 8. Поэлементное объединение строк
arr1 = np.array(['Python', 'PHP'])
arr2 = np.array(['Java', 'C ++'])
combined = np.char.add(arr1, ' ' + arr2)
print("Объединённый массив:", combined)

Объединённый массив: ['Python Java' 'PHP C ++']


In [ ]:
# 9. Подсчёт частоты буквы 'P'
arr = np.array(['Python', 'PHP', 'JS', 'examples', 'html'])
p_counts = np.char.count(arr, 'P')
print("\nЧастота 'P':", p_counts)


Частота 'P': [1 2 0 0 0]


In [ ]:
# 10. Находение корней полиномов

# a) x^2 - 4x + 7
coeffs_a = [1, -4, 7]
roots_a = np.roots(coeffs_a)
print("\nКорни x^2 - 4x + 7:", roots_a)

# b) x^4 - 11x^3 + 9x^2 + 11x - 10
coeffs_b = [1, -11, 9, 11, -10]
roots_b = np.roots(coeffs_b)
print("Корни x^4 - 11x^3 + 9x^2 + 11x - 10:", roots_b)


Корни x^2 - 4x + 7: [2.+1.73205081j 2.-1.73205081j]
Корни x^4 - 11x^3 + 9x^2 + 11x - 10: [10.         -1.          0.99999999  1.00000001]


# №3 (5 баллов)
### Напишите программу, которая будет решать систему линейных уравнений

In [ ]:
import numpy as np

# Ввод данных
print("Введите коэффициенты системы:")
a11 = float(input("a11 = "))
a12 = float(input("a12 = "))
b1 = float(input("b1 = "))

a21 = float(input("a21 = "))
a22 = float(input("a22 = "))
b2 = float(input("b2 = "))

# Создание матриц
A = np.array([[a11, a12], [a21, a22]])
B = np.array([b1, b2])

# Проверка определителя
det = np.linalg.det(A)

if abs(det) < 1e-10:
    print("Система не имеет единственного решения (определитель равен 0)")
else:
    # Решение системы
    solution = np.linalg.solve(A, B)
    print(f"Решение: x = {solution[0]:.4f}, y = {solution[1]:.4f}")

Введите коэффициенты системы:
Решение: x = 2.0000, y = 1.0000
